server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chat_app_db
    username: postgres
    password: vuqar123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jwt:
          secret: mySuperSecretKeyForJwtTokenGenerationThatIsAtLeast32CharactersLong

          spring:
            data:
              redis:
                host: localhost
                port: 6379